// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_secure is a generated GoMock package.
package mock_secure

import (
	context "context"
	secure "gophkeeper/internal/domain/secure"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateSecureData mocks base method.
func (m *MockRepository) CreateSecureData(ctx context.Context, req *secure.SecureDataCreate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecureData", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSecureData indicates an expected call of CreateSecureData.
func (mr *MockRepositoryMockRecorder) CreateSecureData(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecureData", reflect.TypeOf((*MockRepository)(nil).CreateSecureData), ctx, req)
}

// DeleteSecureData mocks base method.
func (m *MockRepository) DeleteSecureData(ctx context.Context, userID string, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecureData", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecureData indicates an expected call of DeleteSecureData.
func (mr *MockRepositoryMockRecorder) DeleteSecureData(ctx, userID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecureData", reflect.TypeOf((*MockRepository)(nil).DeleteSecureData), ctx, userID, id)
}

// GetSecureData mocks base method.
func (m *MockRepository) GetSecureData(ctx context.Context, userID string) ([]secure.SecureData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecureData", ctx, userID)
	ret0, _ := ret[0].([]secure.SecureData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecureData indicates an expected call of GetSecureData.
func (mr *MockRepositoryMockRecorder) GetSecureData(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecureData", reflect.TypeOf((*MockRepository)(nil).GetSecureData), ctx, userID)
}

// UpdateSecureData mocks base method.
func (m *MockRepository) UpdateSecureData(ctx context.Context, req *secure.SecureDataUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecureData", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSecureData indicates an expected call of UpdateSecureData.
func (mr *MockRepositoryMockRecorder) UpdateSecureData(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecureData", reflect.TypeOf((*MockRepository)(nil).UpdateSecureData), ctx, req)
}
