// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_secure is a generated GoMock package.
package mock_secure

import (
	context "context"
	secure "gophkeeper/internal/domain/secure"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateSecureData mocks base method.
func (m *MockService) CreateSecureData(ctx context.Context, req *secure.SecureDataCreate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecureData", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSecureData indicates an expected call of CreateSecureData.
func (mr *MockServiceMockRecorder) CreateSecureData(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecureData", reflect.TypeOf((*MockService)(nil).CreateSecureData), ctx, req)
}

// DeleteSecureData mocks base method.
func (m *MockService) DeleteSecureData(ctx context.Context, userID string, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecureData", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecureData indicates an expected call of DeleteSecureData.
func (mr *MockServiceMockRecorder) DeleteSecureData(ctx, userID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecureData", reflect.TypeOf((*MockService)(nil).DeleteSecureData), ctx, userID, id)
}

// GetSecureData mocks base method.
func (m *MockService) GetSecureData(ctx context.Context, userID string) ([]secure.SecureData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecureData", ctx, userID)
	ret0, _ := ret[0].([]secure.SecureData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecureData indicates an expected call of GetSecureData.
func (mr *MockServiceMockRecorder) GetSecureData(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecureData", reflect.TypeOf((*MockService)(nil).GetSecureData), ctx, userID)
}

// UpdateSecureData mocks base method.
func (m *MockService) UpdateSecureData(ctx context.Context, req *secure.SecureDataUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecureData", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSecureData indicates an expected call of UpdateSecureData.
func (mr *MockServiceMockRecorder) UpdateSecureData(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecureData", reflect.TypeOf((*MockService)(nil).UpdateSecureData), ctx, req)
}
